export const images = {
  bgLogin: require('./image/bg-image.jpg'),
  bgHeader: require('./image/bg-header.png'),
};

export const icons: Partial<IIcons> = {
  home: require('./icons/home.svg'),
  menu: require('./icons/menu.svg'),
  chart: require('./icons/chart.svg'),
  setting: require('./icons/setting.svg'),
  bag: require('./icons/bag.svg'),
  bell: require('./icons/bell.svg'),
  bellWhite: require('./icons/bell-white.svg'),
  dashboard: require('./icons/dashboard.svg'),
  map: require('./icons/map.svg'),
  user: require('./icons/user.svg'),
  navMenuWhite: require('./icons/nav-menu-white.svg'),
  electricity: require('./icons/electricity.svg'),
  exclamation: require('./icons/exclamation.svg'),
  exclamationRed: require('./icons/exclamation-red.svg'),
  pause: require('./icons/pause.svg'),
  arrowRight: require('./icons/arrow-right.svg'),
  repeat: require('./icons/repeat.svg'),
  export: require('./icons/export.svg'),
  exclamationBlack: require('./icons/exclamation-black.svg'),
  filter: require('./icons/filter.svg'),
  arrowLeftWhite: require('./icons/arrow-left-white.svg'),
  irradiance: require('./icons/irradiance.svg'),
  solarPanels: require('./icons/solar-panels.svg'),
  electricityBlue: require('./icons/electricity-blue.svg'),
  checkBlue: require('./icons/check-blue.svg'),
  check: require('./icons/check.svg'),
  arrowDown: require('./icons/arrow-down.svg'),
  arrowUp: require('./icons/arrow-up.svg'),
};
