export const images = {
  bgLogin: require('./image/bg-image.png'),
  bgHeader: require('./image/bg-header.png'),
  drawerHearBg: require('./image/drawer-hear-bg.png'),
  logo: require('./image/logo.png'),
};

export const icons: Partial<IIcons> = {
  home: require('./icons/home.svg'),
  menu: require('./icons/menu.svg'),
  chart: require('./icons/chart.svg'),
  setting: require('./icons/setting.svg'),
  bag: require('./icons/bag.svg'),
  bell: require('./icons/bell.svg'),
  bellWhite: require('./icons/bell-white.svg'),
  dashboard: require('./icons/dashboard.svg'),
  map: require('./icons/map.svg'),
  user: require('./icons/user.svg'),
  navMenuWhite: require('./icons/nav-menu-white.svg'),
  electricity: require('./icons/electricity.svg'),
  exclamation: require('./icons/exclamation.svg'),
  exclamationRed: require('./icons/exclamation-red.svg'),
  pause: require('./icons/pause.svg'),
  arrowRight: require('./icons/arrow-right.svg'),
  repeat: require('./icons/repeat.svg'),
  export: require('./icons/export.svg'),
  exclamationBlack: require('./icons/exclamation-black.svg'),
  filter: require('./icons/filter.svg'),
  arrowLeftWhite: require('./icons/arrow-left-white.svg'),
  irradiance: require('./icons/irradiance.svg'),
  solarPanels: require('./icons/solar-panels.svg'),
  electricityBlue: require('./icons/electricity-blue.svg'),
  checkBlue: require('./icons/check-blue.svg'),
  check: require('./icons/check.svg'),
  arrowDown: require('./icons/arrow-down.svg'),
  arrowUp: require('./icons/arrow-up.svg'),
  close: require('./icons/close.svg'),
  checkGreen: require('./icons/check-green.svg'),
  datePicker: require('./icons/date-picker.svg'),
  download: require('./icons/download.svg'),
  screens: require('./icons/screens.svg'),
  checkRound: require('./icons/check-round.svg'),
  device: require('./icons/device.svg'),
  devices: require('./icons/devices.svg'),
  overview: require('./icons/overview.svg'),
  plus: require('./icons/plus.svg'),
  checkRounded: require('./icons/check-rounded.svg'),
  more: require('./icons/more.svg'),
};

export const iconsImage: Partial<IIcons> = {
  search: require('./icons-image/search.png'),
  bellWhite: require('./icons-image/bellWhite.png'),
  bell: require('./icons-image/bell.png'),
  user: require('./icons-image/user.png'),
  dashboard: require('./icons-image/dashboard.png'),
  map: require('./icons-image/map.png'),
  bag: require('./icons-image/bag.png'),
  chart: require('./icons-image/chart.png'),
  devices: require('./icons-image/devices.png'),
  overview: require('./icons-image/overview.png'),
  exclamation: require('./icons-image/exclamation.png'),
  exclamationRed: require('./icons-image/exclamationRed.png'),
  electricity: require('./icons-image/electricity.png'),
  arrowRight: require('./icons-image/arrowRight.png'),
  pause: require('./icons-image/pause.png'),
  navMenuWhite: require('./icons-image/nav-menu-white.png'),
  menu: require('./icons-image/menu.png'),
  setting: require('./icons-image/setting.png'),
  home: require('./icons-image/home.png'),
  repeat: require('./icons-image/repeat.png'),
  upload: require('./icons-image/upload.png'),
  filter: require('./icons-image/filter.png'),
  arrowLeftWhite: require('./icons-image/arrowLeftWhite.png'),
  back: require('./icons-image/back.png'),
  arrowDown: require('./icons-image/arrow-down.png'),
  datePicker: require('./icons-image/date-picker.png'),
  arrowUp: require('./icons-image/arrow-up.png'),
  checkBlue: require('./icons-image/check-blue.png'),
  plus: require('./icons-image/plus.png'),
  more: require('./icons-image/more.png'),
  download: require('./icons-image/down-load.png'),
  exclamationBlack: require('./icons-image/exclamation-black.png'),
};
