import {StyleSheet} from 'react-native';

export const mainLayoutStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  image: {
    flex: 1,
    justifyContent: 'center',
  },
  content: {
    display: 'flex',
    width: '100%',
    height: '100%',
    flex: 1,
    paddingTop: 50,
  },
  header: {
    flex: 1,
    backgroundColor: 'tranperant',
    width: '100%',
    position: 'relative',
  },
  action: {
    position: 'absolute',
    width: '100%',
    height: 90,
    display: 'flex',
    paddingHorizontal: 24,
    bottom: -30,
    zIndex: 1,
    // backgroundColor: 'blue',
  },
  actionContent: {
    paddingHorizontal: 8,
    shadowColor: '#333',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.5,
    shadowRadius: 3,
    elevation: 20,
    width: '100%',
    borderRadius: 8,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    // backgroundColor: 'blue',
    flex: 1,
  },
  actionContainer: {
    display: 'flex',
    width: '100%',
    height: '100%',
    // backgroundColor: 'blue',
  },
  silderContainer: {
    width: '100%',
    flex: 10,
    paddingBottom: 4,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  silder: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    width: 'auto',
    backgroundColor: '#D9D9D9',
    borderRadius: 10,
    height: 5,
  },
  silderItem: {
    width: 20,
    height: '100%',
    backgroundColor: '#373433',
    borderRadius: 10,
  },
  actionItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  actionIcon: {
    backgroundColor: '#E6EFFC',
    borderRadius: 8,
    height: 40,
    width: 40,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionLable: {
    fontSize: 12,
    color: '#000000',
  },
  headerContent: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 24,
    width: '100%',
    flex: 1,
    gap: 16,
  },
  searchInput: {
    backgroundColor: '#F6F6F6',
    borderRadius: 30,
    flex: 4,
    height: 37,
    paddingLeft: 8,
  },
  headerBtnContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    justifyContent: 'center',
  },
  headerBtn: {
    height: 40,
    width: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    display: 'flex',
  },
  featureIcon: {
    width: 16,
    height: 16,
    position: 'absolute',
    top: 8,
  },
  feature: {
    alignItems: 'center',
  },
  featureName: {
    fontWeight: 'bold',
    fontSize: 12,
    lineHeight: 14,
    color: '#FFFFFF',
    marginTop: 12,
  },
  icon32: {
    width: 32,
    height: 32,
  },
});
